[project]
name = "voxcaster"
version = "0.1.0"
description = "Convert text into audiobookshelf compatible audiobooks"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "piper-tts>=1.3.0",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
